# Shamelessly stolen from Deno's stdlib repository:
# https://github.com/denoland/std/blob/68289312421797e74fac37236cd7eaed1ab0502c/.github/workflows/ci.yml

name: Continuous Integration

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.1.4

            - name: Download Dependencies
              run: deno task deps:cache

            - name: Check Format
              run: deno task check:format

            - name: Check Types
              run: deno task check:types

            - name: Check Lint
              run: deno task check:lint

    test:
        needs: check

        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                    - windows-2022
                    - macOS-14

        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: 2.1.4

            - name: Download Dependencies
              run: deno task deps:cache

            - name: Test
              run: deno task test
